### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by adamretter** [eXist-db/expath-crypto-module#40]
I think this repository should be renamed to something which better described what it is - perhaps `exist-crypto-xar` or something better?

**Comment by joewiz** [comment]
Yes! The current name is a mouthful and unwieldy. How about just `exist-crypto`?

**Comment by adamretter** [comment]
@joewiz I think that is too specific and closes the door on other crypto extensions for eXist-db. I note that the artifact id is `expath-crypto-module` so perhaps we should just name the repo after that? the org `exist-db` then gives the context.

What do you think?

**Comment by windauer** [comment]
I like the idea of renaming this repo and the name: `expath-crypto-module`. Are we only talking of changing the name for this Github repo or the expath-pkg.xml abbrev as well? I would vote for both but we should give it a thought what this means for end users and the public-repo.. And what happens if users install both xars next to each other.... Might be easier to only rename the repo in first place...

**Comment by adamretter** [comment]
@windauer I would suggest just the repo...

**Comment by line-o** [comment]
:+1: for `expath-crypto-module`

**Comment by line-o** [comment]
I would favour `expath-crypto-lib` because it is a library. This is more specific than `module`.

**Comment by joewiz** [comment]
I'll add a vote for `expath-crypto-module`. It has the benefits of already being the artifact id, and in the vernacular, most users think of library modules *as* modules (this is why we ultimately went with xq**m** instead of xq**l** for library modules even though L was a more correct marker of the distinction between the two types of modules).
